# Generated by Django 3.2.8 on 2023-08-18 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_textsumerizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsumerizer',
            name='time_field',
            field=models.TimeField(default=datetime.time(9, 25, 27, 28546)),
        ),
    ]
