# Generated by Django 3.2.8 on 2023-11-27 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230818_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesumerizer',
            name='userid',
        ),
        migrations.AlterField(
            model_name='filesumerizer',
            name='time_field',
            field=models.TimeField(default=datetime.time(8, 42, 47, 919234)),
        ),
        migrations.AlterField(
            model_name='textsumerizer',
            name='time_field',
            field=models.TimeField(default=datetime.time(8, 42, 47, 919234)),
        ),
    ]
